- name: Deleting Deployment
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    resource_group: "iac-war-ansible"
    keyvault_name: "iacwarkv-ansible"
  tasks:
    - name: Delete Key Vault
      azure_rm_keyvault:
        resource_group: "{{ resource_group }}"
        vault_name: "{{ keyvault_name }}"
        state: absent
    - name: Delete Resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        state: absent