apiVersion: azure.microsoft.com/v1alpha1
kind: ResourceGroup
metadata:
  name: iac-war-aso
spec:
  location: westeurope

---
apiVersion: azure.microsoft.com/v1alpha1
kind: KeyVault
metadata:
  name: iacwarkv-aso-net
spec:
  resourceGroup: iac-war-aso
  location: westeurope
  enableSoftDelete: false
  sku:
    name: standard
  networkPolicies:
    bypass: AzureServices
    defaultAction: Allow
  accessPolicies:
    - tenantID: <tenant id>
      objectID: <client id>
      permissions:
        secrets:
          - list
          - get
