apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurekeyvault
spec:
  type: secretstores.azure.keyvault
  metadata:
    - name: vaultName
      value: <AZURE KEY VAULT NAME>
    - name: spnClientId
      value: <MANAGED IDENTITY CLIENT ID>
