apiVersion: v1
kind: Secret
metadata:
  name: redis
type: Opaque
data:
  redisPasssword: YWRtaW4=

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dapr-secret-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-reader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: dapr-test
  - kind: ServiceAccount
    name: default
    namespace: default
