apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
    - name: redisHost
      value: "redis-master.default.svc:6379"
    - name: redisPassword
      secretKeyRef:
        name: redis
    - name: actorStateStore
      value: "true"
auth:
  secretStore: azurekeyvault
