kind: Service
apiVersion: v1
metadata:
  name: secrets
  labels:
    app: secrets
spec:
  selector:
    app: secrets
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets
  labels:
    app: secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secrets
  template:
    metadata:
      labels:
        app: secrets
        aadpodidbinding: reads-vault
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: secrets
        dapr.io/port: "80"
    spec:
      containers:
        - name: secrets
          image: cmendibl3/netcoreconfv2-secrets:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
